### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [nolit1/PhoneBookKonev#1]
1. Определитесь, какие методы являются интерфейсом класса и сделайте их публичными.
2. (относится к п. 1) Можно ли будет использовать ваш класс `obj` снаружи вашего пакета? Если да, то он должен быть публичным (должен ли он при этом быть вложенным?).
3. Приведите имена в соответствие с принятым стилем в Java:
    ```java
    package Books
    ```
    ```java
    class obj
    ```
     ```java
     ArrayList<String> Number
    ````
4. Из названия метода `adnumber` совершенно непонятно, что он делает.
5. Что будет, если в книге несколько человек с одинаковым именем? А с одинаковым номером? 
6. Напишите всё-таки тесты.

**Comment by nolit1** [comment]
Пытался отправить изменения, отправились только тесты... Нажимаю commit, а на отправку ничего не предлагается

**Comment by nolit1** [comment]
Всё, отправил. На счёт тестов хотел бы подойти в четверг

**Comment by gagarski** [comment]
Используя метод `Record.getNumbers()` можно нарушить формат номера, который вы проверяете в конструкторе.
```java
Record r = new Record(/*...*/);
r.getNumbers().add("HELLO");
```
